// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaxKZ_IthF4xv2EZXWsZyu6w5v5JyICtA',
    appId: '1:966207806493:web:1233734f010adc572c3af4',
    messagingSenderId: '966207806493',
    projectId: 'trial-245af',
    authDomain: 'trial-245af.firebaseapp.com',
    storageBucket: 'trial-245af.appspot.com',
    measurementId: 'G-BJG2MZ39NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjZzxZO_ghaoVC_SfnFSijMYqY4biEVBA',
    appId: '1:966207806493:android:35d542eb0f9d309c2c3af4',
    messagingSenderId: '966207806493',
    projectId: 'trial-245af',
    storageBucket: 'trial-245af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxR0LY9s2y4_qUYaz2xL6h-2CmrMyIIHs',
    appId: '1:966207806493:ios:49fe84ad5d37fe5e2c3af4',
    messagingSenderId: '966207806493',
    projectId: 'trial-245af',
    storageBucket: 'trial-245af.appspot.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxR0LY9s2y4_qUYaz2xL6h-2CmrMyIIHs',
    appId: '1:966207806493:ios:955c648a39f9e98b2c3af4',
    messagingSenderId: '966207806493',
    projectId: 'trial-245af',
    storageBucket: 'trial-245af.appspot.com',
    iosBundleId: 'com.example.trial.RunnerTests',
  );
}
